# Site settings
title: Joshua Tan's Code Journey
header-img: img/home-bg.png
email: jtsarvida@gmail.com
copyright_name: JTSarvida
description: > # this means to ignore newlines until "baseurl:"
  English Major to Software Engineer 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JTSarvida
learn_profile: JTSarvida
email_username: jtsarvida@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
